# Generated by Django 3.2.7 on 2021-09-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
