# Generated by Django 3.2.7 on 2021-09-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210924_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
