# Generated by Django 3.2.7 on 2021-09-24 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_useraccount_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
